### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by michabbb** [pinterest/pinlater#1]
hi,

- is there an api ?
- telnet or something ?
- how do you visualize the queus to get an overview, whats going on ?
- can i use pinlater with php ?

thanks!

**Comment by zhiyuanz** [comment]
@michabbb

Thanks for your interest! For your questions:

> is there an api ?

Yes. All APIs are exposed through the Thrift interface, which is defined at [pinlater.thrift] (../blob/master/src/main/thrift/pinlater.thrift)

> telnet or something ?

Unfortunately no.

> how do you visualize the queus to get an overview, whats going on ?

PinLater doesn't have built-in visualization dashboard. Instead, it provides several APIs that monitors/manages queue status, so that users can integrate PinLater with their existing internal dashboard or managing tools. You might want to checkout the following APIs:

* getQueueNames
* getJobCount
* lookupJob
* scanJobs

> can i use pinlater with php ?

Yes. Although PinLater only comes with built-in support for Java, you can still build a PHP thrift client (or any other languages thrift supports) and have full access to the APIs. If you want a full-featured worker, PinLater also comes with an [example java worker](../blob/master/src/main/java/com/pinterest/pinlater/example/PinLaterExampleWorker.java) implementation for reference.

FYI to build PHP thrift client: https://thrift.apache.org/tutorial/php

**Comment by michabbb** [comment]
thanks a lot !

**Comment by beiermosi** [comment]
Hi all, any php client demos here? I can not have the php client work with pinlater using Tsocket connection
